### ISSUE TITLE
Network interface name being treated as float

### ISSUE THREAD

**Issue by neilgierman** [cloudbase/cloudbase-init#133]
In my config, my bond name is "2920" and one of my VLAN IDs is "3900". So the name for that vlan interface is "2920.3900" in my network-config. The problem is, I think cloudbase-init (python) thinks it is a float and is dropping the trailing zeroes and my interface name becomes "2920.39". I don't see a way to tell cloudbase-init to treat the vlan interface name as a string, and don't drop the trailing zeroes.

Minimal config with MACs and IPs removed:
```
version: 1
config:
  - type: physical
    name: eth2
  - type: bond
    name: 2920
    bond_interfaces:
      -  eth2
  - type: vlan
    name: 2920.3900
    vlan_link: 2920
    vlan_id: 3900
```
