### ISSUE TITLE
Using network-config v1, can't have a MAC address with all numbers

### ISSUE THREAD

**Issue by neilgierman** [cloudbase/cloudbase-init#152]
We are still on CloudBase-Init 1.1.4 due to https://github.com/cloudbase/cloudbase-init/issues/147. In testing using kvm, I found that if my VM and network-config has a MAC address with only numbers, CloudBase-Init fails to parse it because "int type doesn't have lower function".

Seems there needs to be some protection that if a MAC is of int type, don't try toLower (or always force the incoming MAC to be string).

My network-config:
```
version: 1
config:
  # multiple interfaces or networks so we need a bond/team NIC
  - type: physical
    name: eth0
    mac_address: 52:54:00:00:00:01
    mtu: 1450
  - type: physical
    name: eth1
    mac_address: 52:54:00:00:00:02
    mtu: 1450
  - type: bond
    name: Default
    mac_address: 52:54:00:00:00:01
    bond_interfaces:
    -  eth0
    -  eth1
    params:
      bond-mode: active-backup
      xmit_hash_policy: layer2
      bond-lacp-rate: false

  # multiple networks with vlans
  - type: vlan
    name: "Default.0"
    vlan_link:  Default
    vlan_id: 0
    subnets:
    - type: static
      address: 192.168.122.200/24
      gateway: 192.168.122.1
      dns_nameservers:
        - 192.168.1.254
```

My virt-install command to bring up the VM:
```
virt-install \
  --name win2022 \
  --memory 2048 \
  --vcpus 2 \
  --disk size=50 \
  --cdrom ./Win2022.iso \
  --os-variant win2k22 \
  --network network=default,mac=52:54:00:00:00:01 \
  --network network=default,mac=52:54:00:00:00:02 \
  --graphics spice,listen=0.0.0.0 \
  --boot uefi \
  --disk path=./win2022.img,format=raw,cache=none,device=floppy
```

From error log:
![image](https://github.com/user-attachments/assets/4ae92d89-4ea2-472a-995b-ad5b122898ac)
