### ISSUE TITLE
Implement cloud-config 'write_files' support

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#25]
Currently, cloud-config 'write_files' has partial support in cloudbase-init.

The following sub-features are not implemented:
  * append (bool: False) - if set, the content given should be appended to the file

Cloud-init docs for 'write_files':
https://cloudinit.readthedocs.io/en/latest/topics/examples.html#writing-out-arbitrary-files

Example cloud-config userdata to be supported:

```yaml
#cloud-config
write_files:
  -
    encoding: b64
    content: CiMgVGhpcyBmaWxlIGNvbnRyb2xzIHRoZSBzdGF0ZSBvZiBTRUxpbnV4
    owner: Administrator
    path: 'C:\\test_file'
    permissions: '0644'
  -
    content: "# Example ps1 file\necho 'test'\n"
    path: 'C:\\test_file.ps1'
  -
    encoding: gzip
    content: null
    path: 'C:\\test_binary'
    permissions: '0555'
  -
    content: "added to file\n"
    path: 'C:\\test_append'
    append: true
```

The key 'owner' will not be implemented on Windows, as there is of little use. The owner of the file will be LocalSystem or the user under which cloudbase-init service runs (defaults to cloudbase-init user, which is an Administrator).
