### ISSUE TITLE
Implement cloud-config 'users' and 'groups' support

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#26]
Cloud-init docs for groups and users:

https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups

Example userdata file:

```yaml
#cloud-config
 
# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group cloud-users.
groups:
  - ubuntu: [root,sys]
  - cloud-users

# Add users to the system. Users are added after groups are added.
users:
  - name: foobar
    gecos: Foo B. Bar
    primary_group: foobar
    groups: users
    passwd: StrongPassw0rd
    inactive: False
    expiredate: 2020-10-01
    ssh_authorized_keys:
      - ssh first key
      - ssh second key
```

The keys following keys are not implemented:
  * homedir - won't do
  * lock_passwd - won't do
  * ssh_redirect_user - won't do
  * ssh_import_id - won't do
  * shell - won't do
  * no_log_init - not a Windows featur
  * no_user_group - not a Windows feature
  * selinux_user - not a Windows feature
  * snapuser - not a Windows feature
  * sudo - not a Windows feature
  * system - not a Windows feature
  * uid - not a Windows feature
