### ISSUE TITLE
Implement cloud-config 'ntp' support

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#28]
Example userdata file:

```yaml
ntp:
  enabled: True
  pools: ['0.company.pool.ntp.org', '1.company.pool.ntp.org', 'ntp.myorg.org']
  servers: ['my.ntp.server.local', 'ntp.ubuntu.com', '192.168.23.2']
```

The keys `ntp_client` and `config` will not be implemented on Windows, as there is only one client with  one way to configure it.
