### ISSUE TITLE
Domain join userdata module

### ISSUE THREAD

**Issue by rhockenbury** [cloudbase/cloudbase-init#30]
For domain joining windows nodes, it would be convenient to have a userdata module.  Currently, this could be done through the `cloudbase-init-unattend.xml`, local scripts plugin, or write_files / runcmd. 

Something like:
```
#cloud-config
domain_join:
  domain_name: domain
  ou_path: ou
  server: server
  username: username
  password: password
```
